name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd pa-mir
          npm install

      - name: Build static site
        run: |
          cd pa-mir
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: '/pa-mir'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pa-mir/out
          destination_dir: pa-mir